[package]
name = "juno-std"
description = "Standard library for Juno with CosmWasm support included. This package is a modified copy of the osmosis package - https://github.com/osmosis-labs/osmosis-rust/tree/main/packages/osmosis-std"
version = "28.0.1"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/CosmosContracts/juno-std"
homepage = "https://junonetwork.io"
readme = "README.md"

[dependencies]
cosmwasm-std = { workspace = true, features = ["cosmwasm_2_2"] }
cosmos-sdk-proto = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde-cw-value = "0.7.0"
schemars = { workspace = true }
serde-json-wasm = { workspace = true }
bech32 = { workspace = true }
thiserror = { workspace = true }
protobuf = { workspace = true }
serde_json = { workspace = true }
cosmwasm-schema = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
tendermint-proto = { workspace = true }
speedate = { workspace = true }
chrono = { version = "0.4.40", default-features = false }
juno-std-derive = "28.0.1"

[dev-dependencies]
base64 = { workspace = true }
prost-types = { workspace = true }
hex = { workspace = true }
