[package]
description = "Procedural macros for `juno-std`. This package is a modified copy of the osmosis package - https://github.com/osmosis-labs/osmosis-rust/tree/main/packages/osmosis-std-derive"
edition = "2021"
license = "Apache-2.0"
name = "juno-std-derive"
version = "28.0.2"

[lib]
proc-macro = true

[dependencies]
itertools = "0.14.0"
proc-macro2 = "1.0.94"
prost-types = { workspace = true }
quote = "1.0.40"
syn = "1.0.109"

[dev-dependencies]
cosmwasm-std = { workspace = true, features = ["cosmwasm_2_2"] }
prost = { workspace = true }
serde = "1.0.219"
trybuild = { version = "1.0.104", features = ["diff"] }
